// <auto-generated />
using System;
using GestorHorario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestorHorario.Migrations
{
    [DbContext(typeof(GestaoHorarioContext))]
    partial class GestaoHorarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestorHorario.Models.Aluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano");

                    b.Property<string>("Email");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("AlunoId");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("GestorHorario.Models.Aluno_Disciplina", b =>
                {
                    b.Property<int>("AlunoId");

                    b.Property<int>("DisciplinaId");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Aluno_Disciplina");
                });

            modelBuilder.Entity("GestorHorario.Models.Disciplina", b =>
                {
                    b.Property<int>("DisciplinaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano");

                    b.Property<bool>("Ativo");

                    b.Property<string>("NomeDisciplina");

                    b.Property<int?>("ProfessorId");

                    b.HasKey("DisciplinaId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplina");
                });

            modelBuilder.Entity("GestorHorario.Models.Horario", b =>
                {
                    b.Property<int>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano");

                    b.Property<DateTime>("Datafim");

                    b.Property<DateTime>("Datainicio");

                    b.HasKey("HorarioId");

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("GestorHorario.Models.Horario_Disciplina", b =>
                {
                    b.Property<int>("HorarioId");

                    b.Property<int>("DisciplinaId");

                    b.Property<string>("Tipo");

                    b.HasKey("HorarioId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Horario_Disciplina");
                });

            modelBuilder.Entity("GestorHorario.Models.Professor", b =>
                {
                    b.Property<int>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<int>("Idade");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Telemovel");

                    b.HasKey("ProfessorId");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("GestorHorario.Models.Aluno_Disciplina", b =>
                {
                    b.HasOne("GestorHorario.Models.Aluno", "Aluno")
                        .WithMany("Aluno_Disciplina")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GestorHorario.Models.Disciplina", "Disciplina")
                        .WithMany("Aluno_Disciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GestorHorario.Models.Disciplina", b =>
                {
                    b.HasOne("GestorHorario.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId");
                });

            modelBuilder.Entity("GestorHorario.Models.Horario_Disciplina", b =>
                {
                    b.HasOne("GestorHorario.Models.Disciplina", "Disciplina")
                        .WithMany("Horario_Disciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GestorHorario.Models.Horario", "Horario")
                        .WithMany("Horario_Disciplinas")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
